### ISSUE TITLE
Add RSS feed

### ISSUE THREAD

**Issue by trishume** [Thinkofname/thinkofname.github.io#8]
I really want to subscribe to your blog and read all your new posts, but that's hard to remember to do if I can't put it in my RSS reader.

See [here](https://github.com/trishume/trishume.github.com/blob/master/atom.xml) for an example of how to add an Atom/RSS feed to a Jekyll site.

**Comment by Thinkofname** [comment]
Sorry about that, I don't use RSS. I've committed something that should generate one once github rebuilds the site.
